dist: trusty

language: node_js
node_js:
  - "8"
  - "9"
  - "10"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install

script:
  - npm run test

notifications:
  email:
    on_success: never
    on_failure: never